services:
    web:
        build: .
        ports:
            - "80:80"
        depends_on:
            - server
        networks:
            - exam-net

    server:
        build: ./server/
        networks:
            - exam-net

networks:
    exam-net:
