services:
    web:
        build: .
        ports:
            - "80:80"
        environment:
            - VITE_BASE_URI=http://server:3000/api
        depends_on:
            - server

    server:
        build: ./server/
        ports:
            - "3000:3000"
